# Generated by Django 5.0 on 2023-12-14 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='borrowBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=150)),
                ('book_name', models.CharField(max_length=20)),
                ('author_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='sellBook',
            fields=[
                ('borrowbook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='books.borrowbook')),
                ('price', models.IntegerField()),
            ],
            bases=('books.borrowbook',),
        ),
    ]
