# Generated by Django 5.0 on 2023-12-14 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0002_remove_user_borrow_books_remove_user_sell_books_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowbook',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='owner_email',
            field=models.EmailField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='borrowbook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='users.user'),
        ),
    ]
