# Generated by Django 5.0 on 2023-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_borrowbook_owner_name_borrowbook_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbook',
            name='book_type',
            field=models.CharField(choices=[('Borrow', 'Borrow'), ('Sell', 'Sell')], default='Borrow', max_length=10),
        ),
    ]
