# Generated by Django 4.2.6 on 2023-10-23 11:48

from django.db import migrations, models
import django.db.models.deletion
import users_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[users_app.models.validate_email]),
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users_app.userk'),
            preserve_default=False,
        ),
    ]
