# Generated by Django 4.2.6 on 2023-10-23 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_userk_alter_user_email_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slug',
            new_name='user',
        ),
    ]
