apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/expruc/kubernetes-gradutaion-drill/k8s-final-drill:frontend
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: BACKENDURL
          value: "http://backend-service:5000"

