# Generated by Django 4.2.6 on 2023-10-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('attack_priority', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enemy_organization', models.CharField(max_length=20)),
                ('target_goal', models.CharField(max_length=30)),
                ('was_target_destroyed', models.BooleanField()),
                ('target_id', models.IntegerField()),
            ],
        ),
    ]
