# Generated by Django 4.2.6 on 2023-10-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='id',
        ),
        migrations.AlterField(
            model_name='target',
            name='latitude',
            field=models.DecimalField(decimal_places=30, max_digits=33),
        ),
        migrations.AlterField(
            model_name='target',
            name='longitude',
            field=models.DecimalField(decimal_places=30, max_digits=33),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
