# Generated by Django 4.2.6 on 2023-10-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='regularEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField()),
                ('close_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('wait_response', 'Wait to Response'), ('wait_handle', 'Wait to Handle')], default='open', max_length=15)),
                ('in_archives', models.BooleanField(default=False)),
                ('toyota', models.CharField(blank=True, editable=False, max_length=500)),
                ('ser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regular_event', to='users.user')),
                ('users_names', models.ManyToManyField(related_name='regular_events', to='users.user')),
            ],
        ),
    ]
