# Generated by Django 4.2.6 on 2023-10-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('fileEvent', '0003_alter_regularevent_toyota'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventWithFiles',
            fields=[
                ('regularevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fileEvent.regularevent')),
                ('upload_date', models.DateField()),
                ('user_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='users.user')),
            ],
            bases=('fileEvent.regularevent',),
        ),
    ]
