# Generated by Django 4.2.6 on 2023-10-24 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('fileEvent', '0004_eventwithfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventWithChat',
            fields=[
                ('regularevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fileEvent.regularevent')),
                ('chat_id', models.IntegerField()),
            ],
            bases=('fileEvent.regularevent',),
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('message_date', models.DateField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='fileEvent.eventwithchat')),
                ('user_send', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='users.user')),
            ],
        ),
    ]
