# Generated by Django 4.2.6 on 2023-10-25 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileEvent', '0005_eventwithchat_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventwithchat',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='eventwithchat',
            name='chat',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chat_event', to='fileEvent.chat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='fileEvent.chat'),
        ),
    ]
