# Generated by Django 4.2.6 on 2023-10-24 09:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, validators=[users.models.validate_email])),
            ],
        ),
    ]
