# Generated by Django 4.2.6 on 2023-10-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_messages',
            field=models.JSONField(default=dict),
        ),
    ]
