# Generated by Django 4.2.6 on 2023-10-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_unread_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_messages',
            field=models.ManyToManyField(to='users.user'),
        ),
    ]
