# Generated by Django 4.2.6 on 2023-10-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_unread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unread_messages',
            field=models.ManyToManyField(blank=True, related_name='unread_for_users', to='users.user'),
        ),
    ]
