# Generated by Django 4.2.6 on 2023-10-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_unread_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unread_messages',
        ),
    ]
