# Generated by Django 5.0 on 2023-12-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='borrow_books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sell_books',
        ),
        migrations.AddField(
            model_name='user',
            name='id_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
