# Generated by Django 4.2.6 on 2023-10-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='kids',
            field=models.ManyToManyField(default=[], related_name='parents', to='person.person'),
        ),
    ]
