# Generated by Django 4.2.6 on 2023-10-19 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_parent_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='salary',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(0)]),
        ),
    ]
