# Generated by Django 4.2.6 on 2023-10-19 13:12

from django.db import migrations
from django.apps import apps


def update_salary_to_integer(apps, schema_editor):
    Parent = apps.get_model('person', 'Parent')
    for parent in Parent.objects.all():
        parent.salary = int(parent.salary)
        parent.save()

class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_alter_parent_salary'),
    ]

    operations = [
        migrations.RunPython(update_salary_to_integer),
    ]
