# Generated by Django 4.2.6 on 2023-10-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20231019_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
